// bridge
export const SET_ONBOARD = 'SET_ONBOARD';
export const SET_NOTIFY = 'SET_NOTIFY';
export const SET_ADDRESS = 'SET_ADDRESS';
export const SET_ENS = 'SET_ENS';
export const SET_NET = 'SET_NET';
export const SET_BALANCE = 'SET_BALANCE';

// app
export const CHANGE_THEME = 'CHANGE_THEME';

export const SET_EXTENSIONS_LIST = 'SET_EXTENSIONS_LIST';
export const SET_CUR_EXT = 'SET_CUR_EXT';

export const CONNECT_WALLET = 'CONNECT_WALLET';
export const CLOSE_CONNECTING = 'CLOSE_CONNECTING';

export const SET_WALLET_IS_CONNECTED = 'SET_WALLET_IS_CONNECTED';

export const SHOW_POPUP = 'SHOW_POPUP';
export const HIDE_POPUP = 'HIDE_POPUP';

export const SHOW_TIP = 'SHOW_TIP';
export const HIDE_TIP = 'HIDE_TIP';
export const CHANGE_TIP_TEXT = 'CHANGE_TIP_TEXT';
export const CHANGE_TIP_DURATION = 'CHANGE_TIP_DURATION';
export const CHANGE_TIP_SEVERITY = 'CHANGE_TIP_SEVERITY';
export const SET_SUBSCRIBE_RECEIVE_TOKENS = 'SET_SUBSCRIBE_RECEIVE_TOKENS';
export const SET_ACCEPTED_PAIR_TOKENS = 'SET_ACCEPTED_PAIR_TOKENS';
export const SET_TIPS = 'SET_TIPS';

// walletSeed
export const SET_SEND_AMOUNT = 'SET_SEND_AMOUNT';
export const SET_SEND_ADDRESS = 'SET_SEND_ADDRESS';
export const SET_SEND_TOKEN = 'SET_SEND_TOKEN';
export const SET_TOKEN_SETTED = 'SET_TOKEN_SETTED';
export const SET_SHOW_ASSETS_FOR_SEND = 'SET_SHOW_ASSETS_FOR_SEND';
export const SET_RECEIVE_TOKEN = 'SET_RECEIVE_TOKEN';
export const SET_RECEIVE_TOKEN_SETTED = 'SET_RECEIVE_TOKEN_SETTED';
export const SET_SHOW_WAITING_SEND_ASSET_POPUP =
  'SET_SHOW_WAITING_SEND_ASSET_POPUP';

// wallet
export const SET_WALLET = 'SET_WALLET';
export const SET_CLIENT_DATA = 'SET_CLIENT_DATA';
export const SET_TOKEN_LIST = 'SET_TOKEN_LIST';
export const SET_PAIRS_LIST = 'SET_PAIRS_LIST';
export const SET_LIQUIDITY_LIST = 'SET_LIQUIDITY_LIST';
export const SET_TRANSACTIONS_LIST = 'SET_TRANSACTIONS_LIST';
export const SET_SUBSCRIBE_DATA = 'SET_SUBSCRIBE_DATA';
export const SET_NFT_ASSETS = 'SET_NFT_ASSETS';
export const SET_INPUT_NFT_DISABLED = 'SET_INPUT_NFT_DISABLED';
export const SET_UPDATED_BALANCE = 'SET_UPDATED_BALANCE';
export const SET_ASSET_LIST_FOR_DEPLOY = 'SET_ASSET_LIST_FOR_DEPLOY';
export const SET_PIN = 'SET_PIN';

// Stacking
export const SHOW_STACKING_CONFIRM_POPUP = 'SHOW_STACKING_CONFIRM_POPUP';
export const HIDE_STACKING_CONFIRM_POPUP = 'HIDE_STACKING_CONFIRM_POPUP';
export const SET_APY_FOR_STACKING = 'SET_APY_FOR_STACKING';
export const SET_AMOUNT_FOR_STACkING = 'SET_AMOUNT_FOR_STACkING';
export const SET_PERIOD_FOR_STACkING = 'SET_PERIOD_FOR_STACkING';
export const SET_SHOW_STAKING_WAITING_POPUP = 'SET_SHOW_STAKING_WAITING_POPUP';

// Client wallets
export const SHOW_CLIENT_WALLETS_FROM_SELECT =
  'SHOW_CLIENT_WALLETS_FROM_SELECT';
export const HIDE_CLIENT_WALLETS_FROM_SELECT =
  'HIDE_CLIENT_WALLETS_FROM_SELECT';

// Pool explorer
export const SHOW_POOL_EXPLORER = 'SHOW_POOL_EXPLORER';
export const HIDE_POOL_EXPLORER = 'HIDE_POOL_EXPLORER';

// Enter seed phrase
export const OPEN_ENTER_SEED = 'OPEN_ENTER_SEED';

export const SHOW_ENTER_SEED_PHRASE = 'SHOW_ENTER_SEED_PHRASE';
export const SET_AFTER_ENTER_SEED_LOADING = 'SET_AFTER_ENTER_SEED_LOADING';
// export const HIDE_ENTER_SEED_PHRASE = 'HIDE_ENTER_SEED_PHRASE';
export const SET_PASSWORD = 'SET_PASSWORD';

export const ENTER_SEED_PHRASE_SIDE = 'ENTER_SEED_PHRASE_SIDE';
export const ENTER_ENCRYPTED_SEED_PHRASE = 'ENTER_ENCRYPTED_SEED_PHRASE';

export const ENTER_SEED_PHRASE_WORD_ONE = 'ENTER_SEED_PHRASE_WORD_ONE';
export const ENTER_SEED_PHRASE_WORD_TWO = 'ENTER_SEED_PHRASE_WORD_TWO';
export const ENTER_SEED_PHRASE_WORD_THREE = 'ENTER_SEED_PHRASE_WORD_THREE';
export const ENTER_SEED_PHRASE_WORD_FOUR = 'ENTER_SEED_PHRASE_WORD_FOUR';
export const ENTER_SEED_PHRASE_WORD_FIVE = 'ENTER_SEED_PHRASE_WORD_FIVE';
export const ENTER_SEED_PHRASE_WORD_SIX = 'ENTER_SEED_PHRASE_WORD_SIX';
export const ENTER_SEED_PHRASE_WORD_SEVEN = 'ENTER_SEED_PHRASE_WORD_SEVEN';
export const ENTER_SEED_PHRASE_WORD_EIGHT = 'ENTER_SEED_PHRASE_WORD_EIGHT';
export const ENTER_SEED_PHRASE_WORD_NINE = 'ENTER_SEED_PHRASE_WORD_NINE';
export const ENTER_SEED_PHRASE_WORD_TEN = 'ENTER_SEED_PHRASE_WORD_TEN';
export const ENTER_SEED_PHRASE_WORD_ELEVEN = 'ENTER_SEED_PHRASE_WORD_ELEVEN';
export const ENTER_SEED_PHRASE_WORD_TWELVE = 'ENTER_SEED_PHRASE_WORD_TWELVE';

export const ENTER_SEED_PHRASE_UNLOCK_SHOW = 'ENTER_SEED_PHRASE_UNLOCK_SHOW';
export const ENTER_SEED_PHRASE_UNLOCK_HIDE = 'ENTER_SEED_PHRASE_UNLOCK_HIDE';

export const ENTER_SEED_PHRASE_REGISTER_SHOW =
  'ENTER_SEED_PHRASE_REGISTER_SHOW';
export const ENTER_SEED_PHRASE_REGISTER_HIDE =
  'ENTER_SEED_PHRASE_REGISTER_HIDE';

export const ENTER_SEED_PHRASE_EMPTY_STORAGE =
  'ENTER_SEED_PHRASE_EMPTY_STORAGE';
export const HIDE_REVEAL_SEED_PHRASE = 'HIDE_REVEAL_SEED_PHRASE';
export const SHOW_REVEAL_SEED_PHRASE = 'SHOW_REVEAL_SEED_PHRASE';

export const ENTER_SEED_PHRASE_SAVE_TO_LOCAL_STORAGE =
  'ENTER_SEED_PHRASE_SAVE_TO_LOCAL_STORAGE';

export const SET_TIP = 'SET_TIP';

// Limit orders
export const SET_LIMIT_ORDER_POPUP_VALUES = 'SET_LIMIT_ORDER_VALUES';
export const RESET_LIMIT_ORDER_POPUP_VALUES = 'RESET_LIMIT_ORDER_VALUES';
export const OPEN_LIMIT_ORDER_CANCEL_POPUP = 'OPEN_LIMIT_ORDER_CANCEL_POPUP';
export const CLOSE_LIMIT_ORDER_CANCEL_POPUP = 'CLOSE_LIMIT_ORDER_CANCEL_POPUP';
export const OPEN_LIMIT_ORDER_DEPLOY_POPUP = 'OPEN_LIMIT_ORDER_DEPLOY_POPUP';
export const CLOSE_LIMIT_ORDER_DEPLOY_POPUP = 'CLOSE_LIMIT_ORDER_DEPLOY_POPUP';
export const OPEN_LIMIT_ORDER_UPDATE_POPUP = 'OPEN_LIMIT_ORDER_UPDATE_POPUP';
export const CLOSE_LIMIT_ORDER_UPDATE_POPUP = 'CLOSE_LIMIT_ORDER_UPDATE_POPUP';

// swap
export const SET_SWAP_POPUP_VALUES = 'SET_SWAP_POPUP_VALUES';
export const RESET_SWAP_POPUP_VALUES = 'RESET_SWAP_POPUP_VALUES';
export const SET_SLIPPAGE = 'SET_SLIPPAGE';

// pool
export const SHOW_POOL_FROM_SELECT = 'SHOW_POOL_FROM_SELECT';
export const HIDE_POOL_FROM_SELECT = 'HIDE_POOL_FROM_SELECT';

export const SHOW_POOL_TO_SELECT = 'SHOW_POOL_TO_SELECT';
export const HIDE_POOL_TO_SELECT = 'HIDE_POOL_TO_SELECT';

export const SET_POOL_FROM_INPUT_VALUE = 'SET_POOL_FROM_INPUT_VALUE';
export const SET_POOL_TO_INPUT_VALUE = 'SET_POOL_TO_INPUT_VALUE';

export const SET_POOL_FROM_TOKEN = 'SET_POOL_FROM_TOKEN';
export const SET_POOL_TO_TOKEN = 'SET_POOL_TO_TOKEN';

export const SET_POOL_PAIR_ID = 'SET_POOL_PAIR_ID';

export const SET_POOL_ASYNC_IS_WAITING = 'SET_POOL_ASYNC_IS_WAITING';

export const SET_POOL_RATE = 'SET_POOL_RATE';

//  manage
export const SET_MANAGE_FROM_TOKEN = 'SET_MANAGE_FROM_TOKEN';
export const SET_MANAGE_TO_TOKEN = 'SET_MANAGE_TO_TOKEN';

export const SET_MANAGE_RATE_AB = 'SET_MANAGE_RATE_AB';
export const SET_MANAGE_RATE_BA = 'SET_MANAGE_RATE_BA';

export const SET_MANAGE_PAIR_ID = 'SET_MANAGE_PAIR_ID';

export const SET_MANAGE_BALANCE = 'SET_MANAGE_BALANCE';

export const SET_MANAGE_ASYNC_IS_WAITING = 'SET_MANAGE_ASYNC_IS_WAITING';

// tokens
export const TOKENS_FETCH_REQUESTED = 'TOKENS_FETCH_REQUESTED';
export const TOKENS_FETCH_LOADING = 'TOKENS_FETCH_LOADING';
export const TOKENS_FETCH_SUCCEEDED = 'TOKENS_FETCH_SUCCEEDED';
export const TOKENS_FETCH_FAILED = 'TOKENS_FETCH_FAILED';
export const RESET_TOKENS = 'RESET_TOKENS';

// pairs
export const PAIRS_FETCH_REQUESTED = 'PAIRS_FETCH_REQUESTED';
export const PAIRS_FETCH_LOADING = 'PAIRS_FETCH_LOADING';
export const PAIRS_FETCH_SUCCEEDED = 'PAIRS_FETCH_SUCCEEDED';
export const PAIRS_FETCH_FAILED = 'PAIRS_FETCH_FAILED';
export const RESET_PAIRS = 'RESET_PAIRS';

// ton context
export const INIT_TON_CONTEXT = 'INIT_TON_CONTEXT';
export const UPDATE_TON_CONTEXT = 'UPDATE_TON_CONTEXT';
export const RESET_TON_CONTEXT = 'RESET_TON_CONTEXT';

// waiting popup
export const SET_WAITING_POPUP_VALUES = 'SET_WAITING_POPUP_VALUES';
export const RESET_WAITING_POPUP_VALUES = 'RESET_WAITING_POPUP_VALUES';

// chrome popup
export const SHOW_CHROME_POPUP = 'SHOW_CHROME_POPUP';
export const HIDE_CHROME_POPUP = 'HIDE_CHROME_POPUP';

// tutorial
export const RESET_TUTORIAL = 'RESET_TUTORIAL';
export const FINISH_TUTORIAL = 'FINISH_TUTORIAL';

// deploy popup
export const SHOW_DEPLOY_POPUP = 'SHOW_DEPLOY_POPUP';
export const HIDE_DEPLOY_POPUP = 'HIDE_DEPLOY_POPUP';
